### ISSUE TITLE
All songs show 0pp

### ISSUE THREAD

**Issue by wesliel** [halsafar/BeatSaberSongDataCore#12] opened 2021-08-16 04:12 UTC
The gzip file referenced in `BeatStarDatabase`: https://cdn.wes.cloud/beatstar/bssb/v2-all.json.gz

Contains 0pp for all songs, therefore ranked song filtering is broken in Song Browser.

Looks like [a similar issue](https://github.com/halsafar/BeatSaberSongDataCore/issues/6) was reported before.

**Comment by wesliel** [comment] 2021-08-16 04:13
![image](https://user-images.githubusercontent.com/3913976/129510560-a6d5c544-b7aa-4b04-ad2f-6fa8ea326477.png)

**Comment by WesVleuten** [comment] 2021-08-16 11:29
Thank you for reporting this, I'll look into it. I'll keep you up to date.

**Comment by WesVleuten** [comment] 2021-08-17 07:28
Bug seems a little more complex than I anticipated, it's gonna take longer. I don't have an ETA.

**Comment by wesliel** [comment] 2021-08-17 21:01
np, thanks for looking into it.
I have lots of web API programming experience, if you need a hand LMK!

**Comment by ChrisJAllan** [comment] 2021-08-21 02:57
The new BeatSaver has an API endpoint to grab the scoreboard of a song with `https://api.beatsaver.com/scores/{hash}/{page}?difficulty={difficulty}&gamemode={gamemode}`, would that help?

(Or, for a cheap estimate, just multiply the stars by 46 or so)

**Comment by WesVleuten** [comment] 2021-08-23 22:43
@ChrisJAllan Thank you for the suggestion, helped lots!

I just pushed an update, I'll be monitoring the server for if anything goes wrong but it should be alright.

**Comment by ErisApps** [comment] 2021-08-27 15:33
Not sure if you noticed it already, but it doesn't look like the update fixed the issue.
Ranked maps still have 0pp
And the "song" and "mapper" fields are still empty for every song (or at least as far as I've checked)

**Comment by wesliel** [comment] 2021-08-27 15:56
Was that a data fix? I just checked the content of v2-all.json.gz and can confirm @ErisApps report.
Does the CDN need a cache purge?

**Comment by ChrisJAllan** [comment] 2021-08-27 16:15
Some songs have a pp value, but something seems very wrong. For example:
[61CAADA06A65088BD514E00D88397CCDEF8C7714.txt](https://github.com/halsafar/BeatSaberSongDataCore/files/7068220/61CAADA06A65088BD514E00D88397CCDEF8C7714.txt)
Has multiple entries for "Easy" difficulty, and no pp on any other difficulty. It also seems that all levels that have non-zero "pp" have zero "star".

So updated information is not replacing old information, ~~and it also only seems to pull the lowest difficulty~~.
Edit: Another example show it does sometimes get other difficulties:
[0CAC133F16A319DE4788AD5F27002994E120D818.txt](https://github.com/halsafar/BeatSaberSongDataCore/files/7068308/0CAC133F16A319DE4788AD5F27002994E120D818.txt)

**Comment by halsafar** [comment] 2021-08-27 18:45
Confirmed, I'm seeing the same issues.

**Comment by halsafar** [comment] 2021-09-01 01:27
PP should be working again.  You might need to delete the files located here: `%USERPROFILE%\AppData\Local\Temp\Hyperbolic Magnetism\Beat Saber\WebCache`

**Comment by halsafar** [comment] 2021-09-02 19:51
Looks like the issue is back again 🥴.  Working on it.

**Comment by halsafar** [comment] 2021-09-06 17:22
Okay, PP is working again (and filter by ranked in SongBrowser).  I'll close this when it appears stable a few others have confirmed.

**Closed as completed** 2021-09-10 03:51 UTC
Labels: bug
